# Content-Based Filtering

Using `ContentBasedRecommender` (TF-IDF on genres) to recommend movies similar to a given title.

In [1]:
import sys
import os
import joblib
import pandas as pd

sys.path.append('..')
from src.utils.data_loader import load_movielens
from src.content_based.tfidf_recommender import ContentBasedRecommender

## 1. Load Data

In [2]:
ratings_df, movies_df = load_movielens(
    ratings_path='../data/raw/u.data',
    movies_path='../data/raw/u.item'
)

print('Ratings shape:', ratings_df.shape)
print('Movies shape:', movies_df.shape)
movies_df.head()

Ratings shape: (100000, 4)
Movies shape: (1682, 22)

,item_id,title,release_date,unknown,Action,Adventure,Animation,Childrens,Comedy,Crime,...,Fantasy,Film_Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0

## 2. Fit the Content-Based Model

In [3]:
content_model = ContentBasedRecommender()
content_model.fit(movies_df)

print('TF-IDF matrix shape:', content_model.tfidf_matrix.shape)
print('Cosine similarity matrix shape:', content_model.cosine_sim.shape)

TF-IDF matrix shape: (1682, 18)
Cosine similarity matrix shape: (1682, 1682)

## 3. Test Recommendations for 5 Different Movies

In [4]:
# Movie 1 — Animation/Children's
print('=== Toy Story (1995) ===')
display(content_model.recommend('Toy Story (1995)', n=10))

=== Toy Story (1995) ===

,title,release_date,similarity_score
0,Aladdin and the King of Thieves (1996),01-Jan-1996,1.000
1,"Aristocats, The (1970)",01-Jan-1970,0.937
2,Pinocchio (1940),01-Jan-1940,0.937
3,"Sword in the Stone, The (1963)",01-Jan-1963,0.937
4,"Fox and the Hound, The (1981)",01-Jan-1981,0.937
5,Winnie the Pooh and the Blustery Day (1968),01-Jan-1968,0.937
6,Balto (1995),01-Jan-1995,0.937
7,Oliver & Company (1988),29-Mar-1988,0.937
8,"Swan Princess, The (1994)",01-Jan-1994,0.937
9,Land Before Time III: The Time of the Great Gi...,01-Jan-1995,0.937

In [5]:
# Movie 2 — Action/Adventure
print('=== GoldenEye (1995) ===')
display(content_model.recommend('GoldenEye (1995)', n=10))

=== GoldenEye (1995) ===

                             title release_date  similarity_score
0                 Rock, The (1996)  07-Jun-1996               1.0
1                   Twister (1996)  10-May-1996               1.0
2  Clear and Present Danger (1994)  01-Jan-1994               1.0
3                  Daylight (1996)  06-Dec-1996               1.0
4            Chain Reaction (1996)  31-Jul-1996               1.0
5              Maximum Risk (1996)  13-Sep-1996               1.0
6                  Anaconda (1997)  11-Apr-1997               1.0
7                   Con Air (1997)  06-Jun-1997               1.0
8                 Firestorm (1998)  09-Jan-1998               1.0
9        Surviving the Game (1994)  01-Jan-1994               1.0

In [6]:
# Movie 3 — Drama
print('=== Fargo (1996) ===')
display(content_model.recommend('Fargo (1996)', n=10))

=== Fargo (1996) ===

                                title release_date  similarity_score
0                        Fargo (1996)  14-Feb-1997            1.0000
1           Desperate Measures (1998)  30-Jan-1998            1.0000
2               Kiss the Girls (1997)  01-Jan-1997            1.0000
3           Desperate Measures (1998)  30-Jan-1998            1.0000
4  Once Upon a Time in America (1984)  01-Jan-1984            1.0000
5                      Amateur (1994)  01-Jan-1994            1.0000
6                Kiss of Death (1995)  01-Jan-1995            1.0000
7                Guilty as Sin (1993)  01-Jan-1993            1.0000
8                Seven (Se7en) (1995)  01-Jan-1995            0.9317
9          Usual Suspects, The (1995)  14-Aug-1995            0.9317

In [7]:
# Movie 4 — Horror/Thriller
print('=== Scream (1996) ===')
display(content_model.recommend('Scream (1996)', n=10))

=== Scream (1996) ===

                                          title release_date  similarity_score
0                                Thinner (1996)  25-Oct-1996               1.0
1                  Village of the Damned (1995)  01-Jan-1995               1.0
2                          Relative Fear (1994)  01-Jan-1994               1.0
3                In the Mouth of Madness (1995)  01-Jan-1995               1.0
4  Halloween: The Curse of Michael Myers (1995)  01-Jan-1995               1.0
5                              Loch Ness (1995)  01-Jan-1995               1.0
6                         Believers, The (1987)  01-Jan-1987               1.0
7                               Scream 2 (1997)  01-Jan-1997               1.0
8                             Nightwatch (1997)  22-Apr-1997               1.0
9                             Nightwatch (1997)  22-Apr-1997               1.0

In [8]:
# Movie 5 — Romance/Comedy
print('=== Jerry Maguire (1996) ===')
display(content_model.recommend('Jerry Maguire (1996)', n=10))

=== Jerry Maguire (1996) ===

                           title release_date  similarity_score
0      Angels and Insects (1995)  01-Jan-1995               1.0
1                Mad Love (1995)  01-Jan-1995               1.0
2              Phenomenon (1996)  29-Jun-1996               1.0
3  Breakfast at Tiffany's (1961)  01-Jan-1961               1.0
4           Graduate, The (1967)  01-Jan-1967               1.0
5     Room with a View, A (1986)  01-Jan-1986               1.0
6           Jerry Maguire (1996)  13-Dec-1996               1.0
7             Chasing Amy (1997)  01-Jan-1997               1.0
8        Pillow Book, The (1995)  13-Jun-1997               1.0
9             Chasing Amy (1997)  01-Jan-1997               1.0

## 4. Analysis — Do Recommendations Make Sense?

- **Toy Story** → Returns other Animation/Children's/Comedy movies ✅
- **GoldenEye** → Returns other Action/Adventure/Thriller movies ✅
- **Fargo** → Returns Crime/Drama/Thriller movies ✅
- **Scream** → Returns other Horror/Thriller movies ✅
- **Jerry Maguire** → Returns Romance/Comedy/Drama movies ✅

The TF-IDF model correctly groups movies by genre. Limitation: it cannot account for user preferences or movie quality — purely genre-driven.

## 5. Save the Content Model

In [9]:
os.makedirs('../models', exist_ok=True)
joblib.dump(content_model, '../models/content_model.pkl')
print('content_model.pkl saved to models/')

content_model.pkl saved to models/